---
title: "Project 3: project3part1package tutorial"
author: "Alexander Thomson"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{project3part1package Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

```{r setup}
library(project3part1package)
```

You should put your introuctory paragraph here!!!!

# Student's T-test

```{r}
data(my_gapminder)

my_data <- my_gapminder$lifeExp
```

```{r}
my_t.test(x = my_data, alternative = "two.sided", mu = 60)
```

```{r}
my_t.test(x = my_data, alternative = "less", mu = 60)
```

```{r}
my_t.test(x = my_data, alternative = "greater", mu = 60)
```

# Fitting Linear Models

```{r}
my_fit <- my_lm(lifeExp ~ gdpPercap + continent, data = my_gapminder)
my_fit
```

```{r}
my_intercept <- my_fit[1, 1]
my_gdpPercap <- my_fit[2, 1]
my_america_coeff <- my_fit[3, 1]
my_asia_coeff <- my_fit[4, 1]
my_europe_coeff <- my_fit[5, 1]
my_oceania_coeff <- my_fit[6, 1]

my_gapminder$predicted <- my_intercept + (my_gdpPercap * my_gapminder$gdpPercap) + (my_america_coeff * (my_gapminder$continent == "Americas")) + (my_asia_coeff * (my_gapminder$continent == "Asia")) + (my_europe_coeff * (my_gapminder$continent == "Europe")) + (my_oceania_coeff * (my_gapminder$continent == "Oceania"))

ggplot2::ggplot(my_gapminder, ggplot2::aes(predicted, lifeExp, color = continent)) +
  ggplot2::geom_point()
```

# K-Nearest Neighbors Cross Validation

```{r}
# load the penguins data
data(my_penguins)

# remove NAs from penguins
penguins_no_NA <- stats::na.omit(my_penguins)
# separate the covariates and the true classification
my_data <- data.frame("bill_length" = penguins_no_NA$bill_length_mm,
                      "bill_depth" = penguins_no_NA$bill_depth_mm,
                      "flipper_length" = penguins_no_NA$flipper_length_mm,
                      "body_mass" = penguins_no_NA$body_mass_g)
my_cl <- penguins_no_NA$species

train_miss <- c()
cv_miss <- c()

# find the training and cv misclassification rates for k_nn from 1 through 10
for (k_nn in 1:10) {
  my_knn_cv_out <- my_knn_cv(data = my_data, cl = my_cl, k_nn = k_nn, k_cv = 5)
  train_miss[k_nn] <- mean(my_knn_cv_out[[1]] != my_cl)
  cv_miss[k_nn] <- my_knn_cv_out[[2]]
}

# create a table with the results
my_table <- data.frame(k_nn = 1:10,
                       cv_err = round(cv_miss, 4),
                       train_err = round(train_miss, 4))
kableExtra::kable_styling(kableExtra::kable(my_table))
```

# Random Forests Cross Validation

```{r}
my_cv_MSEs <- matrix(NA, nrow = 30, ncol = 3)
counter <- 1
for (k in c(2, 5, 10)) {
  k_MSE <- c()
  for (i in 1:30) {
    k_MSE[i] <- my_rf_cv(k)
  }
  my_cv_MSEs[, counter] <- k_MSE
  counter <- counter + 1
}
cv_MSEs_data <- data.frame("cv_MSE" = c(my_cv_MSEs[, 1], my_cv_MSEs[, 2], my_cv_MSEs[, 3]),
                                "k" = c(rep(2, 30), rep(5, 30), rep(10, 30)))
cv_MSEs_data[, 2] <- as.factor(cv_MSEs_data[, 2])
```

```{r}
ggplot2::ggplot(cv_MSEs_data, ggplot2::aes(x = k, y = cv_MSE)) +
  ggplot2::geom_boxplot()
```

```{r}
my_MSE_table <- matrix(NA, nrow = 3, ncol = 2)

my_MSE_table[1, 1] <- mean(my_cv_MSEs[, 1])
my_MSE_table[2, 1] <- mean(my_cv_MSEs[, 2])
my_MSE_table[3, 1] <- mean(my_cv_MSEs[, 3])

my_MSE_table[1, 2] <- sd(my_cv_MSEs[, 1])
my_MSE_table[2, 2] <- sd(my_cv_MSEs[, 2])
my_MSE_table[3, 2] <- sd(my_cv_MSEs[, 3])

my_MSE_table <- data.frame(my_MSE_table)
colnames(my_MSE_table) <- c("mean", "standard deviation")
rownames(my_MSE_table) <- c("2", "5", "10")

kableExtra::kable_styling(kableExtra::kable(my_MSE_table))
```








